name: Steem Load Balancer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: NODE_ENV=production npm run lint

      - name: Set up environment
        run: |
          source ./setup-env.sh
          echo "STEEM_LB_PATH=$STEEM_LB_PATH" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
          echo "NODE_ENV=$NODE_ENV" >> $GITHUB_ENV
          echo "RETRY_COUNT=$RETRY_COUNT" >> $GITHUB_ENV
          echo "SSL_CERT_PATH=$SSL_CERT_PATH" >> $GITHUB_ENV
          echo "SSL_KEY_PATH=$SSL_KEY_PATH" >> $GITHUB_ENV
          echo "HOST_PORT=$HOST_PORT" >> $GITHUB_ENV

      - name: Run unit tests
        run: NODE_ENV=production npm test

      - name: Run integration tests
        run: |
          cd ./tests/
          ./run-tests.sh ./integration-tests.sh

      - name: Run integration tests (Empty Nodes in config.yaml)
        run: |
          cd ./tests/
          ./run-tests.sh ./integration-tests-empty-nodes.sh

      - name: Run integration tests (No Valid Nodes in config.yaml)
        run: |
          cd ./tests/
          echo "No valid node found"
          ./run-tests.sh ./integration-tests-error-nodes.sh

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run integration tests (Docker Compose)
        run: |
          cd ./tests/
          ./run-tests.sh ./integration-tests-docker-compose.sh
